language: objective-c

osx_image: xcode8.0

podfile: RYImagePicker/Podfile

before_install:
    - rvm use system
    

script: 
- xctool -workspace RYImagePicker/RYImagePicker.xcworkspace -scheme RYImagePicker -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
##- xcodebuild -workspace RYImagePicker/RYImagePicker.xcworkspace -scheme RYImagePickerTests -sdk iphonesimulator test
